-- CreateTable
CREATE TABLE `Hit` (
    `index` INTEGER NOT NULL,
    `box1` VARCHAR(191) NOT NULL,
    `box2` VARCHAR(191) NOT NULL,
    `box3` VARCHAR(191) NOT NULL,
    `box4` VARCHAR(191) NOT NULL,
    `box5` VARCHAR(191) NOT NULL,
    `box6` VARCHAR(191) NOT NULL,
    `box7` VARCHAR(191) NOT NULL,
    `box8` VARCHAR(191) NOT NULL,
    `box9` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`index`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
